version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: hospital_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7001:7001"
    environment:
      - RAILS_ENV=test
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/hospital_test
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      bash -c "
        bundle exec rails db:create db:migrate &&
        bundle exec rails test
      "

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "7002:7002"
    environment:
      - RAILS_ENV=test
      - API_BASE_URL=http://backend:7001
    depends_on:
      - backend
    command: >
      bash -c "
        bundle exec rails test:system
      "

volumes:
  postgres_test_data: